resources:
  - rook/cluster/examples/kubernetes/ceph/common.yaml
  - rook/cluster/examples/kubernetes/ceph/operator.yaml
  - rook/cluster/examples/kubernetes/ceph/cluster.yaml
  - rook/cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml

patchesStrategicMerge:
  # patches rook to use 'directories' instead of partitions.
  # comment out to use partitions
  - patch_cephcluster.yaml
  - patch_cephblockpool.yaml
